### ISSUE TITLE
Documentation is hard to understand

### ISSUE THREAD

**Issue by PorridgeKiller** [tympanix/electron-regedit#1]
Very bad Documentation!!!

**Comment by tympanix** [comment]
I am sorry you did not find the documentation helpful. Can you elaborate on why the documentation was unclear and how you would increase the readability? Do you need more examples or more detailed descriptions?

**Comment by tympanix** [comment]
@PorridgeKiller bump

**Comment by PorridgeKiller** [comment]
I'm sorry for being unfamiliar with regedit function of windows, it's my fault.
For electron, I think people prefer to use regedit in easier ways such as set/get/delete rather than write windows shell scripts to operate the registry. 
> [rage-edit](https://github.com/MikeKovarik/rage-edit) is a good solution for operating reg keys.   
> But finally I chose [node-winreg](https://github.com/fresc81/node-winreg) as my own solution.

Your project is a good solution for people who are professional. 
                                   Thanks for your reply~

**Comment by tympanix** [comment]
No worries. Actually you may view this project as a wrapper for [node-winreg](https://github.com/fresc81/node-winreg) which abstracts away the problem of setting the right keys in the right locations. This also means you would never set/get/delete the keys by yourself, as it is handled for you. I certainly think you should go with [node-winreg](https://github.com/fresc81/node-winreg) for more control in this case. Cheers.
