### ISSUE TITLE
ProgId `squirrel` options doesn't work

### ISSUE THREAD

**Issue by bendemboski** [tympanix/electron-regedit#4]
Setting `squirrel: true` in a `ProgId` will not make its `ShellOption`s' `squirrel` options default to `true`:

```sh
> const { ProgId } = require('electron-regedit')
undefined
> new ProgId({ appName: 'foo', squirrel: true, extensions: [ 'cst' ] })
ProgId {
  progId: 'foo',
  appName: 'foo',
  description: undefined,
  hive: 'HKCU',
  icon: undefined,
  squirrel: true,
  friendlyAppName: undefined,
  extensions: [ 'cst' ],
  shell: [
    ShellOption {
      verb: 'open',
      action: undefined,
      selected: false,
      friendlyAppName: undefined,
      icon: undefined,
      args: [Array],
      squirrel: false,
      command: undefined,
      progid: [Circular]
    }
  ],
  BASE_KEY: '\\Software\\Classes\\foo'
}
```

I believe this is happening because in `ShellOption()`, the `squirrel` argument [defaults to](https://github.com/tympanix/electron-regedit/blob/master/progid.js#L14) `false`, but in `ShellOption.bindProg()`, it only uses its `ProgId`'s `squirrel` value if `squirrel` [is undefined](https://github.com/tympanix/electron-regedit/blob/master/progid.js#L39) rather than `false`.

**Comment by tympanix** [comment]
You are correct. I think we should have no problem setting the default squirrel value to undefined [here](https://github.com/tympanix/electron-regedit/blob/2ff046e093492ec8676250f9f8347b0b4911957b/shelloption.js#L14), such that it will be properly overwritten.
