### ISSUE TITLE
Is there a way to add additional parameters, such as URL Protocol

### ISSUE THREAD

**Issue by andreas-gruenwald** [tympanix/electron-regedit#5]
See screenshot.
![image](https://user-images.githubusercontent.com/16687355/84501670-2f40f400-acb7-11ea-8be6-8b001812509f.png)

I didn't find a way to specific the "URL Protocol" parameter.

**Comment by tympanix** [comment]
If you want to register protocol handlers, I think you should use this instead: https://www.electronjs.org/docs/api/protocol

Sorry for my late reply.

**Comment by auver** [comment]
Electron protocol API is only works in Electron application.
 `app.setAsDefaultProtocolClient(protocol[, path, args])` add URL Protocol in system

**Comment by tympanix** [comment]
Right, thanks for clearing that up 👍
